<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260727120919 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, domaine VARCHAR(255) NOT NULL, type_document VARCHAR(100) NOT NULL, score_confiance INT DEFAULT NULL, date_depot DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_document_domaine ON document (domaine)');
        $this->addSql('CREATE TABLE echeance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(200) NOT NULL, date_echeance DATE NOT NULL, montant_centimes INT DEFAULT NULL, type_montant VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_echeance_date ON echeance (date_echeance)');
        $this->addSql('CREATE TABLE facture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, tiers VARCHAR(200) NOT NULL, montant_centimes INT NOT NULL, statut VARCHAR(255) NOT NULL, date_emission DATE NOT NULL, e_facture BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_facture_statut ON facture (statut)');
        $this->addSql('CREATE UNIQUE INDEX uniq_facture_numero ON facture (numero)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE echeance');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
