<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260727145513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, priorite VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_action_priorite ON action (priorite)');
        $this->addSql('CREATE TABLE alerte_encaissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tiers VARCHAR(200) NOT NULL, montant_centimes INT NOT NULL, statut VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_alerte_statut ON alerte_encaissement (statut)');
        $this->addSql('CREATE TABLE article_blog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(150) NOT NULL, titre VARCHAR(200) NOT NULL, chapo VARCHAR(300) NOT NULL, contenu TEXT NOT NULL, auteur VARCHAR(120) NOT NULL, date_publication DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_article_date ON article_blog (date_publication)');
        $this->addSql('CREATE UNIQUE INDEX uniq_article_slug ON article_blog (slug)');
        $this->addSql('CREATE TABLE flux_tresorerie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mois_label VARCHAR(30) NOT NULL, position INT NOT NULL, entrees_centimes INT NOT NULL, sorties_centimes INT NOT NULL, solde_centimes INT NOT NULL, realise BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_flux_position ON flux_tresorerie (position)');
        $this->addSql('CREATE TABLE professionnel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(200) NOT NULL, cabinet VARCHAR(200) DEFAULT NULL, domaine VARCHAR(255) NOT NULL, specialite VARCHAR(200) DEFAULT NULL, delai_indicatif VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_professionnel_domaine ON professionnel (domaine)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, creneau TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirme BOOLEAN NOT NULL, professionnel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A8A49CC82 ON rendez_vous (professionnel_id)');
        $this->addSql('CREATE INDEX idx_rdv_creneau ON rendez_vous (creneau)');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A8A49CC82 FOREIGN KEY (professionnel_id) REFERENCES professionnel (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A8A49CC82');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE alerte_encaissement');
        $this->addSql('DROP TABLE article_blog');
        $this->addSql('DROP TABLE flux_tresorerie');
        $this->addSql('DROP TABLE professionnel');
        $this->addSql('DROP TABLE rendez_vous');
    }
}
